spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://101.200.193.2:3306/confluence-dev?serverTimezone=GMT%2B8
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    database: 10
    host: 101.200.193.2
    port: 6379
    timeout: 5000